language: java
jdk:
  - openjdk11

sudo: required

service:
  - mysql

dist: xenial

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"


before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS matchnow;'



notifications:
  email:
    recipients:
      - sendmailtest991@gmail.com