language: java
jdk:
  - openjdk11

sudo: required

service:
  - mysql

dist: xenial

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS matchnow;'

before_deploy:
  - zip -r matchnow *
  - mkdir -p deploy
  - mv matchnow.zip deploy/matchnow.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: spring-build123
    region: us-west-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: spring-build123
    key: matchnow.zip
    bundle_type: zip
    application: matchnow
    deployment_group: matchnow-group
    region: us-west-2
    wait-until-deployed: true


notifications:
  email:
    recipients:
      - sendmailtest991@gmail.com